@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTU5OTY5MzQsImV4cCI6MTc1NjAwMDUzNH0.tmZE1TLDziW4McFUUE4AcaYdCYGkja6HkADs6W_Wh6Q
@detailId = 9

### Create new booking detail
POST http://{{host}}/booking-details
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "service_id": "3",
    "booking_id": "3",
}

### Update booking detail
PATCH http://{{host}}/booking-details/{{detailId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "booking_id": "3",
    "service_id": "3",
    "price": "120000",
    "duration": "40"
}

### Delete booking detail
DELETE http://{{host}}/booking-details/{{detailId}}
Authorization: Bearer {{accessToken}}

### Get all booking details
GET http://{{host}}/booking-details

### Get one booking detail
GET http://{{host}}/booking-details/{{detailId}}
