@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTU5OTY5MzQsImV4cCI6MTc1NjAwMDUzNH0.tmZE1TLDziW4McFUUE4AcaYdCYGkja6HkADs6W_Wh6Q

### Create new service
POST http://{{host}}/services
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "admin_id": "1",
    "category_id": "1",
    "name": "Cắt tóc nam",
    "image": "https://example.com/image.jpg",
    "duration": "30",
    "price": "100000",
    "description": "Dịch vụ cắt tóc nam chuyên nghiệp"
}

### Update service
PATCH http://{{host}}/services/{{serviceId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "Cắt tóc nam cao cấp",
    "status": "approved",
    "price": "150000"
}

### Delete service
DELETE http://{{host}}/services/{{serviceId}}
Authorization: Bearer {{accessToken}}

### Get all services
GET http://{{host}}/services

### Get one service
GET http://{{host}}/services/{{serviceId}}
