@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTU5OTY5MzQsImV4cCI6MTc1NjAwMDUzNH0.tmZE1TLDziW4McFUUE4AcaYdCYGkja6HkADs6W_Wh6Q
@reasonId = 3

### Create new booking reason
POST http://{{host}}/booking-reasons
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "booking_id": "3",
    "reason": "Khách bận đột xuất"
}

### Update booking reason
PATCH http://{{host}}/booking-reasons/{{reasonId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "booking_id": "3",
    "reason": "Khách đổi lịch"
}

### Delete booking reason
DELETE http://{{host}}/booking-reasons/{{reasonId}}
Authorization: Bearer {{accessToken}}

### Get all booking reasons
GET http://{{host}}/booking-reasons

### Get one booking reason
GET http://{{host}}/booking-reasons/{{reasonId}}
